<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<link rel="stylesheet" type="text/css" href="index.css" />
<title>pzs-ng: Project Zipscript Next Generation (.%country mirror) - disclaimer.</title>
</head>
<body>
<b>DISCLAIMER:</b><br>
<ul>
	<li>The tools, programs and sourcecode (from here referred to as 'software') found on www.pzs-ng.com or any of it's official mirrors are for educational purposes only.</li>
	<li>The software offered can only be downloaded and/or used if not violating any laws in the respective country/countries.</li>
	<li>The authors of the software, owners of the webservers and their respective ISP's cannot be held responsible for the use or misuse, directly or indirectly, of the content offered.</li>
	<li>The software offered is work-in-progress, and should be considered as such. There is no guarantee the software will work as expected, desired or even described.</li>
	<li>Any document or sourcecode that links to this disclaimer, presenting it as such, is covered by these clauses.</li>
	<li>Should any part of this disclaimer be unclear, please contact us by email at <a href="mailto:disclaimer@pzs-ng.com">disclaimer@pzs-ng.com</a> for further explanations.</li>
</ul>
<br>
Back to <a href="http://%country.pzs-ng.com">our website</a>.<br>
Meet us at <a target=_blank href="http://www.efnet.org">EFnet</a> channel #pzs-ng<br>
Page generated by <a href='http://daxxar.com'>template-mirror</a> at %time_of_generation.<br>
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-1352913-1";
urchinTracker();
</script>
</body>
</html>
