<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<link rel="stylesheet" type="text/css" href="index.css" />
<title>pzs-ng: Project Zipscript Next Generation (.%country mirror)</title>
</head>
<body>
Welcome to pzs-ng (Project Zipscript - Next Generation)<br>
<div class="mirror_links">mirrors: %mirror_links</div><br>
You must agree to <a href="disclaimer.html">this disclaimer</a> before using any of the offered resources.<br><br>
<br>
<a target=_blank href="http://bugs.pzs-ng.com/">Bugtracker</a><br>
<br>
<!-- <a target=_blank href="ftp://pzs-ng.ftpd.gl/">Public FTP</a> Updated every 5 mins.<br> -->
<a target=_blank href="ftp://pzs-ng:pzs-ng@ftp.pzs-ng.com:21021/">Public FTP</a> Updated every 15 mins.<br>
<!-- <a target=_blank href="svn://svnmirror.pzs-ng.com/project-zs-ng/branches/pzs-ng_v1/trunk/">Public SVN</a> Updated every hour.<br> -->
<a target=_blank href="http://svn.pzs-ng.com/project-zs-ng/branches/pzs-ng_v1/trunk/">SVN repository</a> This is our repository, you can check out using 'svn co http://svn.pzs-ng.com/project-zs-ng/branches/pzs-ng_v1/trunk/'.<br>
<br>
Newest unstable: %newest_file{unstable} (note, this page is updated at manual intervals)<br>
Newest stable: %newest_file{stable} (note, this page is updated at manual intervals)<br><br>
<br>
Read <a href='http://wzdftpd.net/trac/wiki/Documentation/ThirdPartyScripts/pzs-ng'>http://wzdftpd.net/trac/wiki/Documentation/ThirdPartyScripts/pzs-ng</a> for information on setting up pzs-ng under wzdftpd (EXPERIMENTAL).<br>
Patch for 1.0.1 -> 1.0.1b: <a href="pzs-ng_v1.0.1b_patch.diff">pzs-ng_v1.0.1b_patch.diff</a>. Read comments in file for info on patching.<br>
Patch for 1.0   -> 1.0.1: <a href="pzs-ng_v1.0.1_patch.diff">pzs-ng_v1.0.1_patch.diff</a>. Read comments in file for info on patching.<br>
<br><br>
Our quotes: <a href="quotes.html">quotes.html</a>
<br>
Random quote:<br>
%random_quote
<br> <br>
<span class="keyword">DEFINITIONS</span>:<br>
------------<br>
&nbsp; - <span class="keyword">STABLE</span>:&nbsp;&nbsp; Thoroughly tested by several people for &gt;14days, containing no known bugs.<br>
&nbsp; - <span class="keyword">TESTING</span>:&nbsp; Revisions in a frozen state, thought to be stable at the time, but not tested by several people for &gt;14 days.<br>
&nbsp; - <span class="keyword">UNSTABLE</span>: Still on testing stage, but usable. All known bugs are either listed on the bugtracker, or fixed.<br>
&nbsp; - <span class="keyword">VOLATILE</span>: Work in progress. Might work, might not. Not considered suitable to be used.<br>
&nbsp; - <span class="keyword">UNUSABLE</span>: Revisions found to contain bugs which severly hinder the use of the script. (should never be listed under downloads)<br>
<br>
<div class="file_links">
<h2>Stable</h2>
%file_links{stable, o }
<h2>Testing</h2>
%file_links{testing, o }
<h2>Unstable</h2>
%file_links{unstable, o }
<h2>Volatile</h2>
%file_links{volatile, o }
</div><br>
--------------------------------<br>
<br>
Meet us at <a target=_blank href="http://www.efnet.org">EFnet</a> channel #pzs-ng<br>
Page generated by <a href='http://daxxar.com'>template-mirror</a> at %time_of_generation.<br>
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-1352913-1";
urchinTracker();
</script>
</body>
</html>
