<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<link rel="stylesheet" type="text/css" href="index.css" />
<title>pzs-ng: Project Zipscript Next Generation (.%country mirror)</title>
</head>
<body>
Welcome to pzs-ng (Project Zipscript - Next Generation) quotes<br>
<div class="mirror_links">main page: <a href="index.html">index.html</a></div><br>
%quotes
<br>
Meet us at <a target=_blank href="http://www.efnet.org">EFnet</a> channel #pzs-ng<br>
Page generated by <a href='http://daxxar.com'>template-mirror</a> at %time_of_generation.<br>
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-1352913-1";
urchinTracker();
</script>
</body>
</html>
